Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /botsitech/component2/request/
"GET /botsitech/component2/request/ HTTP/1.1" 400 72058
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 71948
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 71948
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/urls.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 72053
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/manage.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 72053
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/manage.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 72053
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/project/wsgi.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /component2/request/
"GET /component2/request/ HTTP/1.1" 400 72053
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/project/settings/production.py changed, reloading.
Watching for file changes with StatReloader
"GET /component2/request/ HTTP/1.1" 200 0
Internal Server Error: /component2/request/
Traceback (most recent call last):
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/leonardo/Documentos/other projects/03_skeleton_djangorest/env_project/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Orders is not JSON serializable
"GET /component2/request/ HTTP/1.1" 500 102621
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/view.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/view.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/models.py changed, reloading.
Watching for file changes with StatReloader
"GET /component2/request/ HTTP/1.1" 200 163
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/view.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/leonardo/Documentos/other projects/03_skeleton_djangorest/project/apps/integration/component2/models.py changed, reloading.
Watching for file changes with StatReloader
